### ISSUE TITLE
Result are inconsistent with SearchUrlCommand(s)

### ISSUE THREAD

**Issue by tuleism** [reibitto/command-center#36] opened 2020-07-29 11:53 UTC
In this case, Google `prefixPreview` seems to work correctly:

![Screenshot 2020-07-29 at 19 50 53](https://user-images.githubusercontent.com/6073387/88796815-e399c980-d1d4-11ea-9e29-283767471202.png)

In this case, DuckDuckGo should be the first result. It seems the `prefixPreview`'s result got lost:

![Screenshot 2020-07-29 at 19 46 38](https://user-images.githubusercontent.com/6073387/88796479-4d65a380-d1d4-11ea-81a1-1107ebbf58e5.png)

**Comment by reibitto** [comment] 2020-07-29 12:17
This is definitely a bug. I'll need to investigate.

Also almost no work has gone into making accurate scores. That needs to be addressed eventually. But I think that might be unrelated to this.

**Comment by reibitto** [comment] 2020-07-30 11:12
This is now fixed.

The cause was that in application.conf `commandNames` was set to `["ddg" "duckduckgo"]` instead of `["ddg", "duckduckgo"]`. Apparently HOCON doesn't work like Clojure. 😛

But I'm a little surprised `["ddg" "duckduckgo"]` get's intepreted as `List("ddg duckduckgo")`. I'm not sure if that's a bug or part of the HOCON specification. I'd rather it have fail...

**Closed by reibitto** 2020-07-30 11:12 UTC
